apiVersion: v2
name: postgresql
description: A Helm chart that references the official "postgresql" Helm chart.
type: application
version: 16.7.15
dependencies:
  - name: postgresql
    version: 16.7.15
    repository: https://charts.bitnami.com/bitnami
